<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Potatos-Mac.local" name="TestCases.ServiceManagementTest" tests="5" failures="1" timestamp="2021-02-05T18:57:59 WIB" time="20.491" errors="0">
  <testcase name="signIn" time="4.287" classname="TestCases.ServiceManagementTest"/>
  <testcase name="R01_ViewServiceManagement" time="1.543" classname="TestCases.ServiceManagementTest"/>
  <testcase name="R02_SearchServiceManagement" time="4.942" classname="TestCases.ServiceManagementTest"/>
  <testcase name="R03_ApproveService" time="0.612" classname="TestCases.ServiceManagementTest"/>
  <testcase name="R04_RejectService" time="9.107" classname="TestCases.ServiceManagementTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Service is not deactivated did not expect to find [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Service is not deactivated did not expect to find [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at TestCases.ServiceManagementTest.R04_RejectService(ServiceManagementTest.java:119)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:41)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:443)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:67)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- R04_RejectService -->
</testsuite> <!-- TestCases.ServiceManagementTest -->
